"use client";

import Header from "@/components/Header";
import Reveal from "@/components/Reveal";

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-background text-foreground transition-colors duration-500 font-outfit pb-20">
      <Header />
      
      <section className="pt-40 pb-20 px-6">
        <div className="max-w-3xl mx-auto">
          <Reveal>
            <h1 className="text-4xl md:text-6xl font-black mb-8 tracking-tight">
              Privacy <span className="gradient-text">Policy</span>
            </h1>
            <p className="text-muted-foreground mb-12 italic">Last Updated: April 4, 2026</p>
          </Reveal>

          <Reveal delay={0.1}>
            <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none space-y-8">
              <section>
                <h2 className="text-xl font-bold mb-4">1. Information We Collect</h2>
                <p>We collect information you provide directly to us, such as when you create an account, book a service, or communicate with our Superheroes. This may include your name, email, phone number, and the contact details of your gift recipients.</p>
              </section>

              <section>
                <h2 className="text-xl font-bold mb-4">2. Voice Recordings & Media</h2>
                <p>For our 'Digital Letter' service, we may store audio recordings provided by you or generated by our hosts. These recordings are stored securely and are only accessible by the intended recipient via the unique link provided to them.</p>
              </section>

              <section>
                <h2 className="text-xl font-bold mb-4">3. How We Use Your Information</h2>
                <p>We use the information we collect to provide, maintain, and improve our services, including to process transactions, send confirmations, and respond to your comments or questions.</p>
              </section>

              <section>
                <h2 className="text-xl font-bold mb-4">4. Data Sharing</h2>
                <p>We do not sell your personal data. We only share information with third-party service providers (like Paystack for payments or Supabase for data storage) necessary to deliver our services.</p>
              </section>

              <section className="p-8 rounded-3xl glass border border-primary/20 bg-primary/5">
                <h2 className="text-xl font-bold mb-4 text-primary">5. Contact Us</h2>
                <p className="mb-0">If you have any questions about this Privacy Policy, please contact our Superhero Support Team at hello@buzzthrillsprime.com.</p>
              </section>
            </div>
          </Reveal>
        </div>
      </section>
    </main>
  );
}
